export default {
  'component---site-src-pages-index-jsc-4-f-f99': [() => import(/* webpackChunkName: 'component---site-src-pages-index-jsc-4-f-f99' */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  'component---theme-debugd-45-c28': [() => import(/* webpackChunkName: 'component---theme-debugd-45-c28' */ "@theme/Debug"), "@theme/Debug", require.resolveWeak("@theme/Debug")],
  'component---theme-doc-item-178-a40': [() => import(/* webpackChunkName: 'component---theme-doc-item-178-a40' */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  'component---theme-doc-page-1-be-9be': [() => import(/* webpackChunkName: 'component---theme-doc-page-1-be-9be' */ "@theme/DocPage"), "@theme/DocPage", require.resolveWeak("@theme/DocPage")],
  'content---wandisco-documentation-ldm-docs-3-d-8-0f9': [() => import(/* webpackChunkName: 'content---wandisco-documentation-ldm-docs-3-d-8-0f9' */ "@site/docs/about.md"), "@site/docs/about.md", require.resolveWeak("@site/docs/about.md")],
  'content---wandisco-documentation-ldm-docs-api-reference-964-3df': [() => import(/* webpackChunkName: 'content---wandisco-documentation-ldm-docs-api-reference-964-3df' */ "@site/docs/api-reference.md"), "@site/docs/api-reference.md", require.resolveWeak("@site/docs/api-reference.md")],
  'content---wandisco-documentation-ldm-docs-command-reference-669-e7c': [() => import(/* webpackChunkName: 'content---wandisco-documentation-ldm-docs-command-reference-669-e7c' */ "@site/docs/command-reference.md"), "@site/docs/command-reference.md", require.resolveWeak("@site/docs/command-reference.md")],
  'content---wandisco-documentation-ldm-docs-configuration-9-ed-9de': [() => import(/* webpackChunkName: 'content---wandisco-documentation-ldm-docs-configuration-9-ed-9de' */ "@site/docs/configuration.md"), "@site/docs/configuration.md", require.resolveWeak("@site/docs/configuration.md")],
  'content---wandisco-documentation-ldm-docs-getting-startedd-58-99b': [() => import(/* webpackChunkName: 'content---wandisco-documentation-ldm-docs-getting-startedd-58-99b' */ "@site/docs/getting-started.md"), "@site/docs/getting-started.md", require.resolveWeak("@site/docs/getting-started.md")],
  'content---wandisco-documentation-ldm-docs-operationcce-960': [() => import(/* webpackChunkName: 'content---wandisco-documentation-ldm-docs-operationcce-960' */ "@site/docs/operation.md"), "@site/docs/operation.md", require.resolveWeak("@site/docs/operation.md")],
  'content---wandisco-documentation-ldm-docs-quickstart-807-41e': [() => import(/* webpackChunkName: 'content---wandisco-documentation-ldm-docs-quickstart-807-41e' */ "@site/docs/quickstart.md"), "@site/docs/quickstart.md", require.resolveWeak("@site/docs/quickstart.md")],
  'content---wandisco-documentation-ldm-docs-readme-52-e-edd': [() => import(/* webpackChunkName: 'content---wandisco-documentation-ldm-docs-readme-52-e-edd' */ "@site/docs/readme.md"), "@site/docs/readme.md", require.resolveWeak("@site/docs/readme.md")],
  'docsMetadata---wandisco-documentation-ldm-docsd-02-e5f': [() => import(/* webpackChunkName: 'docsMetadata---wandisco-documentation-ldm-docsd-02-e5f' */ "~docs/wandisco-documentation-ldm-docs-route-1d0.json"), "~docs/wandisco-documentation-ldm-docs-route-1d0.json", require.resolveWeak("~docs/wandisco-documentation-ldm-docs-route-1d0.json")],};
